version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - database

  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./database:/data/db

  frontend:
    build: ./frontend
    ports:
      - "8081:8081"  # Corrected ports mapping for the frontend service
